#!/bin/sh
set -e

BASENAME=$(basename $0)
DIRNAME=$(dirname $0)

# If no options are specified, display help
if [ $# -eq 0 ]; then
  echo "Usage: ${BASENAME} [ctx1|ctx2|ctx3] [args]"
  echo "  gh mix ctx1    # hello world by c"
  echo "  gh mix ctx2    # hello world by rust"
  echo "  gh mix ctx3    # hello world by shellscript"
  exit 1
fi

# ex: 1.0.0
NEW_VERSION=$(cat ${DIRNAME}/manifest.yml | grep "tag" | awk '{print $2}')
if [  -f ${DIRNAME}/VERSION ]; then
  OLD_VERSION=$(cat ${DIRNAME}/VERSION)
else
  OLD_VERSION="0.0.0"
fi

if [ ${OLD_VERSION} != ${NEW_VERSION} ]; then
  echo "--------------------------------------"
  echo "バージョンが変更されました。"
  echo "OLD_VERSION=${OLD_VERSION}"
  echo "NEW_VERSION=${NEW_VERSION}"
  echo "--------------------------------------"
  echo "gh-mixをインストールします。"
  echo "--------------------------------------"
  # ex: linux-amd64
  ARTIFACT="linux-amd64"
  ASSET_URL="https://github.com/kouji-sasaya/gh-mix/releases/download/${NEW_VERSION}/gh-mix_${NEW_VERSION}_${ARTIFACT}.tar.gz"
  curl --silent -L "${ASSET_URL}" -o "${DIRNAME}/gh-mix.tar.gz"
  cd ${DIRNAME}
  tar xf gh-mix.tar.gz
  cd -
else
  echo "--------------------------------------"
  echo "バージョンは変更されていません。"
  echo "OLD_VERSION=${OLD_VERSION}"
  echo "NEW_VERSION=${NEW_VERSION}"
  echo "--------------------------------------"
fi


if [ "${1}" = "ctx1" ]; then
  ${DIRNAME}/bin/gh-mix-ctx1 $@
  exit
fi

if [ "${1}" = "ctx2" ]; then
  ${DIRNAME}/bin/gh-mix-ctx2 $@
  exit
fi

if [ "${1}" = "ctx3" ]; then
  ${DIRNAME}/bin/gh-mix-ctx3 $@
  exit
fi
