#!/bin/sh
set -e

BASENAME=$(basename $0)
DIRNAME=$(dirname $0)


# ex: 1.0.0
NEW_VERSION=$(cat ${DIRNAME}/manifest.yml | grep "tag" | awk '{print $2}')
if [  -f ${DIRNAME}/VERSION ]; then
  OLD_VERSION=$(cat ${DIRNAME}/VERSION)
else
  OLD_VERSION="0.0.0"
fi

if [ ${OLD_VERSION} != ${NEW_VERSION} ]; then
  echo "--------------------------------------"
  echo "バージョンが変更されました。"
  echo "OLD_VERSION=${OLD_VERSION}"
  echo "NEW_VERSION=${NEW_VERSION}"
  echo "--------------------------------------"
  echo "gh-mixをインストールします。"
  echo "--------------------------------------"
  # ex: linux-amd64
  ARTIFACT="linux-amd64"
  ASSET_URL="https://github.com/kouji-sasaya/gh-mix/releases/download/${NEW_VERSION}/gh-mix_${NEW_VERSION}_${ARTIFACT}.tar.gz"
  curl --silent -L "${ASSET_URL}" -o "${DIRNAME}/gh-mix.tar.gz"
  cd ${DIRNAME}
  tar xf gh-mix.tar.gz
  cd -
fi


# If no options are specified, display help
if [ $# -eq 0 ]; then
  echo "Usage: ${BASENAME} [c|rust|sh] [args]"
  echo "  gh mix c    # hello world by c"
  echo "  gh mix rust # hello world by rust"
  echo "  gh mix sh   # hello world by shellscript"
  exit 1
fi

if [ "${1}" = "c" ]; then
  ${DIRNAME}/bin/gh-mix-c $@
  exit
fi

if [ "${1}" = "rust" ]; then
  ${DIRNAME}/bin/gh-mix-rust $@
  exit
fi

if [ "${1}" = "sh" ]; then
  ${DIRNAME}/bin/gh-mix-sh $@
  exit
fi

echo "Invalid sub command: ${1}"
exit 1