name: Release

permissions:
  contents: write

on:
  push:
    tags:
      # セマンティックバージョンのタグをリリースする。vなし
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Configure the project
        run: cmake -S . -B build

      - name: Build the project
        run: cmake --build build --config Release

      - name: Package the project
        run: cmake --build build --target package

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: build/gh-mix-1.0.0-Linux.tar.gz
          asset_name: gh-mix_${{ github.ref_name }}_linux_amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}